Section.delete_all
Book.delete_all
Parsha.delete_all
Pasuk.delete_all
Aliya.delete_all

# Section.first.books.first.perakim.first.pesukim.first.aliyos
# Aliya.first.pesukim

# Section

torah = Section.create(id: 1, title_en: "Torah", title_he: "תורה", title_he_tr: "Torah", description: "The Torah")
neviim = Section.create(id: 2, title_en: "Prophets", title_he: "נביאים", title_he_tr: "Neviim", description: "The Neviim")
kesuvim = Section.create(id: 3, title_en: "Writings", title_he: "כתובים", title_he_tr: "Kesuvim", description: "The Kesuvim")

# Book
seferBereishit = Book.create(title_en: 'Genesis', title_he: 'בראשית', title_he_tr: 'Bereishit', description: 'The book of Bereishit', section_id: torah.id)
seferShemot = Book.create(title_en: 'Exodus', title_he: 'שמות', title_he_tr: 'Shemot', description: 'The book of Shemot', section_id: torah.id)
seferVayikra = Book.create(title_en: 'Leviticus', title_he: 'ויקרא', title_he_tr: 'Vayikra', description: 'The book of Vayikra', section_id: torah.id)
seferBamidbar = Book.create(title_en: 'Numbers', title_he: 'במדבר', title_he_tr: 'Bamidbar', description: 'The book of Bamidbar', section_id: torah.id)
seferDevarim = Book.create(title_en: 'Deuteronomy', title_he: 'דברים', title_he_tr: 'Devarim', description: 'The book of Devarim', section_id: torah.id)
seferYehoshua = Book.create(title_en: 'Joshua', title_he: 'יהושע', title_he_tr: 'Yehoshua', description: 'The book of Yehoshua', section_id: neviim.id)
seferShoftim = Book.create(title_en: 'Judges', title_he: 'שופטים', title_he_tr: 'Shoftim', description: 'The book of Shoftim', section_id: neviim.id)
seferShmuel_I = Book.create(title_en: 'I Samuel', title_he: 'שמואל א', title_he_tr: 'Shmuel I', description: 'The book of Shmuel I', section_id: neviim.id)
seferShmuel_II = Book.create(title_en: 'II Samuel', title_he: 'שמואל ב', title_he_tr: 'Shmuel II', description: 'The book of Shmuel II', section_id: neviim.id)
seferMelachim_I = Book.create(title_en: 'I Kings', title_he: 'מלכים א', title_he_tr: 'Melachim I', description: 'The book of Melachim I', section_id: neviim.id)
seferMelachim_II = Book.create(title_en: 'II Kings', title_he: 'מלכים ב', title_he_tr: 'Melachim II', description: 'The book of Melachim II', section_id: neviim.id)
seferYeshayahu = Book.create(title_en: 'Isaiah', title_he: 'ישעיה', title_he_tr: 'Yeshayahu', description: 'The book of Yeshayahu', section_id: neviim.id)
seferYirmiyahu = Book.create(title_en: 'Jeremiah', title_he: 'ירמיה', title_he_tr: 'Yirmiyahu', description: 'The book of Yirmiyahu', section_id: neviim.id)
seferYechezkel = Book.create(title_en: 'Ezekiel', title_he: 'יחזקאל', title_he_tr: 'Yechezkel', description: 'The book of Yechezkel', section_id: neviim.id)
seferHoshea = Book.create(title_en: 'Hosea', title_he: 'הושע', title_he_tr: 'Hoshea', description: 'The book of Hoshea', section_id: neviim.id)
seferYoel = Book.create(title_en: 'Joel', title_he: 'יואל', title_he_tr: 'Yoel', description: 'The book of Yoel', section_id: neviim.id)
seferAmos = Book.create(title_en: 'Amos', title_he: 'עמוס', title_he_tr: 'Amos', description: 'The book of Amos', section_id: neviim.id)
seferOvadiah = Book.create(title_en: 'Obadiah', title_he: 'עובדיה', title_he_tr: 'Ovadiah', description: 'The book of Ovadiah', section_id: neviim.id)
seferYonah = Book.create(title_en: 'Jonah', title_he: 'יונה', title_he_tr: 'Yonah', description: 'The book of Yonah', section_id: neviim.id)
seferMichah = Book.create(title_en: 'Micah', title_he: 'מיכה', title_he_tr: 'Michah', description: 'The book of Michah', section_id: neviim.id)
seferNachum = Book.create(title_en: 'Nahum', title_he: 'נחום', title_he_tr: 'Nachum', description: 'The book of Nachum', section_id: neviim.id)
seferChavakuk = Book.create(title_en: 'Habakkuk', title_he: 'חבקוק', title_he_tr: 'Chavakuk', description: 'The book of Chavakuk', section_id: neviim.id)
seferTzefaniah = Book.create(title_en: 'Zephaniah', title_he: 'צפניה', title_he_tr: 'Tzefaniah', description: 'The book of Tzefaniah', section_id: neviim.id)
seferChaggai = Book.create(title_en: 'Haggai', title_he: 'חגי', title_he_tr: 'Chaggai', description: 'The book of Chaggai', section_id: neviim.id)
seferZechariah = Book.create(title_en: 'Zechariah', title_he: 'זכריה', title_he_tr: 'Zechariah', description: 'The book of Zechariah', section_id: neviim.id)
seferMalachi = Book.create(title_en: 'Malachi', title_he: 'מלאכי', title_he_tr: 'Malachi', description: 'The book of Malachi', section_id: neviim.id)
seferTehillim = Book.create(title_en: 'Psalms', title_he: 'תהלים', title_he_tr: 'Tehillim', description: 'The book of Tehillim', section_id: kesuvim.id)
seferMishlei = Book.create(title_en: 'Proverbs', title_he: 'משלי', title_he_tr: 'Mishlei', description: 'The book of Mishlei', section_id: kesuvim.id)
seferIyov = Book.create(title_en: 'Job', title_he: 'איוב', title_he_tr: 'Iyov', description: 'The book of Iyov', section_id: kesuvim.id)
seferShir_Hashirim = Book.create(title_en: 'Song of Songs', title_he: 'שיר השירים', title_he_tr: 'Shir Hashirim', description: 'The book of Shir Hashirim', section_id: kesuvim.id)
seferRut = Book.create(title_en: 'Ruth', title_he: 'רות', title_he_tr: 'Rut', description: 'The book of Rut', section_id: kesuvim.id)
seferEichah = Book.create(title_en: 'Lamentations', title_he: 'איכה', title_he_tr: 'Eichah', description: 'The book of Eichah', section_id: kesuvim.id)
seferKohelet = Book.create(title_en: 'Ecclesiastes', title_he: 'קהלת', title_he_tr: 'Kohelet', description: 'The book of Kohelet', section_id: kesuvim.id)
seferEsther = Book.create(title_en: 'Esther', title_he: 'אסתר', title_he_tr: 'Esther', description: 'The book of Esther', section_id: kesuvim.id)
seferDaniel = Book.create(title_en: 'Daniel', title_he: 'דניאל', title_he_tr: 'Daniel', description: 'The book of Daniel', section_id: kesuvim.id)
seferEzra = Book.create(title_en: 'Ezra', title_he: 'עזרא', title_he_tr: 'Ezra', description: 'The book of Ezra', section_id: kesuvim.id)
seferNechemiah = Book.create(title_en: 'Nehemiah', title_he: 'נחמיה', title_he_tr: 'Nechemiah', description: 'The book of Nechemiah', section_id: kesuvim.id)
seferDivrei_Hayamim_I = Book.create(title_en: 'I Chronicles', title_he: 'דברי הימים א', title_he_tr: 'Divrei Hayamim I', description: 'The book of Divrei Hayamim I', section_id: kesuvim.id)
seferDivrei_Hayamim_II = Book.create(title_en: 'II Chronicles', title_he: 'דברי הימים ב', title_he_tr: 'Divrei Hayamim II', description: 'The book of Divrei Hayamim II', section_id: kesuvim.id)


# Parsha
בראשית = Parsha.create(book_id: seferBereishit.id, title_he: "בראשית", title_en: "", title_he_tr: "", description: "Parshas בראשית")
נח = Parsha.create(book_id: seferBereishit.id, title_he: "נח", title_en: "", title_he_tr: "", description: "Parshas נח")
לך_לך = Parsha.create(book_id: seferBereishit.id, title_he: "לך-לך", title_en: "", title_he_tr: "", description: "Parshas לך-לך")
וירא = Parsha.create(book_id: seferBereishit.id, title_he: "וירא", title_en: "", title_he_tr: "", description: "Parshas וירא")
חיי_שרה = Parsha.create(book_id: seferBereishit.id, title_he: "חיי-שרה", title_en: "", title_he_tr: "", description: "Parshas חיי-שרה")
תולדות = Parsha.create(book_id: seferBereishit.id, title_he: "תולדות", title_en: "", title_he_tr: "", description: "Parshas תולדות")
ויצא = Parsha.create(book_id: seferBereishit.id, title_he: "ויצא", title_en: "", title_he_tr: "", description: "Parshas ויצא")
וישלח = Parsha.create(book_id: seferBereishit.id, title_he: "וישלח", title_en: "", title_he_tr: "", description: "Parshas וישלח")
וישב = Parsha.create(book_id: seferBereishit.id, title_he: "וישב", title_en: "", title_he_tr: "", description: "Parshas וישב")
מקץ = Parsha.create(book_id: seferBereishit.id, title_he: "מקץ", title_en: "", title_he_tr: "", description: "Parshas מקץ")
ויגש = Parsha.create(book_id: seferBereishit.id, title_he: "ויגש", title_en: "", title_he_tr: "", description: "Parshas ויגש")
ויחי = Parsha.create(book_id: seferBereishit.id, title_he: "ויחי", title_en: "", title_he_tr: "", description: "Parshas ויחי")
שמות = Parsha.create(book_id: seferShemot.id, title_he: "שמות", title_en: "", title_he_tr: "", description: "Parshas שמות")
וארא = Parsha.create(book_id: seferShemot.id, title_he: "וארא", title_en: "", title_he_tr: "", description: "Parshas וארא")
בא = Parsha.create(book_id: seferShemot.id, title_he: "בא", title_en: "", title_he_tr: "", description: "Parshas בא")
בשלח = Parsha.create(book_id: seferShemot.id, title_he: "בשלח", title_en: "", title_he_tr: "", description: "Parshas בשלח")
יתרו = Parsha.create(book_id: seferShemot.id, title_he: "יתרו", title_en: "", title_he_tr: "", description: "Parshas יתרו")
משפטים = Parsha.create(book_id: seferShemot.id, title_he: "משפטים", title_en: "", title_he_tr: "", description: "Parshas משפטים")
תרומה = Parsha.create(book_id: seferShemot.id, title_he: "תרומה", title_en: "", title_he_tr: "", description: "Parshas תרומה")
תצוה = Parsha.create(book_id: seferShemot.id, title_he: "תצוה", title_en: "", title_he_tr: "", description: "Parshas תצוה")
כי_תשא = Parsha.create(book_id: seferShemot.id, title_he: "כי-תשא", title_en: "", title_he_tr: "", description: "Parshas כי-תשא")
ויקהל = Parsha.create(book_id: seferShemot.id, title_he: "ויקהל", title_en: "", title_he_tr: "", description: "Parshas ויקהל")
פקודי = Parsha.create(book_id: seferShemot.id, title_he: "פקודי", title_en: "", title_he_tr: "", description: "Parshas פקודי")
ויקהל_פקודי = Parsha.create(book_id: seferShemot.id, title_he: "ויקהל-פקודי", title_en: "", title_he_tr: "", description: "Parshas ויקהל-פקודי")
ויקרא = Parsha.create(book_id: seferVayikra.id, title_he: "ויקרא", title_en: "", title_he_tr: "", description: "Parshas ויקרא")
צו = Parsha.create(book_id: seferVayikra.id, title_he: "צו", title_en: "", title_he_tr: "", description: "Parshas צו")
שמיני = Parsha.create(book_id: seferVayikra.id, title_he: "שמיני", title_en: "", title_he_tr: "", description: "Parshas שמיני")
תזריע = Parsha.create(book_id: seferVayikra.id, title_he: "תזריע", title_en: "", title_he_tr: "", description: "Parshas תזריע")
מצורע = Parsha.create(book_id: seferVayikra.id, title_he: "מצורע", title_en: "", title_he_tr: "", description: "Parshas מצורע")
תזריע_מצורע = Parsha.create(book_id: seferVayikra.id, title_he: "תזריע-מצורע", title_en: "", title_he_tr: "", description: "Parshas תזריע-מצורע")
אחרי_מות = Parsha.create(book_id: seferVayikra.id, title_he: "אחרי-מות", title_en: "", title_he_tr: "", description: "Parshas אחרי-מות")
קדושים = Parsha.create(book_id: seferVayikra.id, title_he: "קדושים", title_en: "", title_he_tr: "", description: "Parshas קדושים")
אחרי_מות_קדושים = Parsha.create(book_id: seferVayikra.id, title_he: "אחרי-מות-קדושים", title_en: "", title_he_tr: "", description: "Parshas אחרי-מות-קדושים")
אמור = Parsha.create(book_id: seferVayikra.id, title_he: "אמור", title_en: "", title_he_tr: "", description: "Parshas אמור")
בהר = Parsha.create(book_id: seferVayikra.id, title_he: "בהר", title_en: "", title_he_tr: "", description: "Parshas בהר")
בחקתי = Parsha.create(book_id: seferVayikra.id, title_he: "בחקתי", title_en: "", title_he_tr: "", description: "Parshas בחקתי")
בהר_בחקתי = Parsha.create(book_id: seferVayikra.id, title_he: "בהר-בחקתי", title_en: "", title_he_tr: "", description: "Parshas בהר-בחקתי")
במדבר = Parsha.create(book_id: seferBamidbar.id, title_he: "במדבר", title_en: "", title_he_tr: "", description: "Parshas במדבר")
נשא = Parsha.create(book_id: seferBamidbar.id, title_he: "נשא", title_en: "", title_he_tr: "", description: "Parshas נשא")
בהעלתך = Parsha.create(book_id: seferBamidbar.id, title_he: "בהעלתך", title_en: "", title_he_tr: "", description: "Parshas בהעלתך")
שלח = Parsha.create(book_id: seferBamidbar.id, title_he: "שלח", title_en: "", title_he_tr: "", description: "Parshas שלח")
קרח = Parsha.create(book_id: seferBamidbar.id, title_he: "קרח", title_en: "", title_he_tr: "", description: "Parshas קרח")
חקת = Parsha.create(book_id: seferBamidbar.id, title_he: "חקת", title_en: "", title_he_tr: "", description: "Parshas חקת")
בלק = Parsha.create(book_id: seferBamidbar.id, title_he: "בלק", title_en: "", title_he_tr: "", description: "Parshas בלק")
חקת_בלק = Parsha.create(book_id: seferBamidbar.id, title_he: "חקת-בלק", title_en: "", title_he_tr: "", description: "Parshas חקת-בלק")
פנחס = Parsha.create(book_id: seferBamidbar.id, title_he: "פנחס", title_en: "", title_he_tr: "", description: "Parshas פנחס")
מטות = Parsha.create(book_id: seferBamidbar.id, title_he: "מטות", title_en: "", title_he_tr: "", description: "Parshas מטות")
מסעי = Parsha.create(book_id: seferBamidbar.id, title_he: "מסעי", title_en: "", title_he_tr: "", description: "Parshas מסעי")
מטות_מסעי = Parsha.create(book_id: seferBamidbar.id, title_he: "מטות-מסעי", title_en: "", title_he_tr: "", description: "Parshas מטות-מסעי")
דברים = Parsha.create(book_id: seferDevarim.id, title_he: "דברים", title_en: "", title_he_tr: "", description: "Parshas דברים")
ואתחנן = Parsha.create(book_id: seferDevarim.id, title_he: "ואתחנן", title_en: "", title_he_tr: "", description: "Parshas ואתחנן")
עקב = Parsha.create(book_id: seferDevarim.id, title_he: "עקב", title_en: "", title_he_tr: "", description: "Parshas עקב")
ראה = Parsha.create(book_id: seferDevarim.id, title_he: "ראה", title_en: "", title_he_tr: "", description: "Parshas ראה")
שופטים = Parsha.create(book_id: seferDevarim.id, title_he: "שופטים", title_en: "", title_he_tr: "", description: "Parshas שופטים")
כי_תצא = Parsha.create(book_id: seferDevarim.id, title_he: "כי-תצא", title_en: "", title_he_tr: "", description: "Parshas כי-תצא")
כי_תבא = Parsha.create(book_id: seferDevarim.id, title_he: "כי-תבא", title_en: "", title_he_tr: "", description: "Parshas כי-תבא")
נצבים = Parsha.create(book_id: seferDevarim.id, title_he: "נצבים", title_en: "", title_he_tr: "", description: "Parshas נצבים")
וילך = Parsha.create(book_id: seferDevarim.id, title_he: "וילך", title_en: "", title_he_tr: "", description: "Parshas וילך")
נצבים_וילך = Parsha.create(book_id: seferDevarim.id, title_he: "נצבים-וילך", title_en: "", title_he_tr: "", description: "Parshas נצבים-וילך")
האזינו = Parsha.create(book_id: seferDevarim.id, title_he: "האזינו", title_en: "", title_he_tr: "", description: "Parshas האזינו")
וזאת_הברכה = Parsha.create(book_id: seferDevarim.id, title_he: "וזאת-הברכה", title_en: "", title_he_tr: "", description: "Parshas וזאת-הברכה")

# Pasuk

records = JSON.parse(File.read('tanach.json'))
records.each do |record|
  book = Book.find_by(title_en: record['seferEn'])
  Pasuk.create!(text_he: record['txt'], text_en: "not available", unkelos: "not available", number: record['pasuknum'], perek: record['perekNum'], book_id: book.id)
end

# Aliya
Aliya.create(aliyah_number: 1, parsha_id: בראשית.id, start_perek: 1,start_pasuk: 1, end_perek: 2, end_pasuk: 3 )
Aliya.create(aliyah_number: 2, parsha_id: בראשית.id, start_perek: 2,start_pasuk: 4, end_perek: 2, end_pasuk: 19 )
Aliya.create(aliyah_number: 3, parsha_id: בראשית.id, start_perek: 2,start_pasuk: 20, end_perek: 3, end_pasuk: 21 )
Aliya.create(aliyah_number: 4, parsha_id: בראשית.id, start_perek: 3,start_pasuk: 22, end_perek: 4, end_pasuk: 18 )
Aliya.create(aliyah_number: 5, parsha_id: בראשית.id, start_perek: 4,start_pasuk: 19, end_perek: 4, end_pasuk: 22 )
Aliya.create(aliyah_number: 6, parsha_id: בראשית.id, start_perek: 4,start_pasuk: 23, end_perek: 5, end_pasuk: 24 )
Aliya.create(aliyah_number: 7, parsha_id: בראשית.id, start_perek: 5,start_pasuk: 25, end_perek: 6, end_pasuk: 8 )
Aliya.create(aliyah_number: 8, parsha_id: בראשית.id, start_perek: 6,start_pasuk: 5, end_perek: 6, end_pasuk: 8 )
Aliya.create(aliyah_number: 1, parsha_id: נח.id, start_perek: 6,start_pasuk: 9, end_perek: 6, end_pasuk: 22 )
Aliya.create(aliyah_number: 2, parsha_id: נח.id, start_perek: 7,start_pasuk: 1, end_perek: 7, end_pasuk: 16 )
Aliya.create(aliyah_number: 3, parsha_id: נח.id, start_perek: 7,start_pasuk: 17, end_perek: 8, end_pasuk: 14 )
Aliya.create(aliyah_number: 4, parsha_id: נח.id, start_perek: 8,start_pasuk: 15, end_perek: 9, end_pasuk: 7 )
Aliya.create(aliyah_number: 5, parsha_id: נח.id, start_perek: 9,start_pasuk: 8, end_perek: 9, end_pasuk: 17 )
Aliya.create(aliyah_number: 6, parsha_id: נח.id, start_perek: 9,start_pasuk: 18, end_perek: 10, end_pasuk: 32 )
Aliya.create(aliyah_number: 7, parsha_id: נח.id, start_perek: 11,start_pasuk: 1, end_perek: 11, end_pasuk: 32 )
Aliya.create(aliyah_number: 8, parsha_id: נח.id, start_perek: 11,start_pasuk: 29, end_perek: 11, end_pasuk: 32 )
Aliya.create(aliyah_number: 1, parsha_id: לך_לך.id, start_perek: 12,start_pasuk: 1, end_perek: 12, end_pasuk: 13 )
Aliya.create(aliyah_number: 2, parsha_id: לך_לך.id, start_perek: 12,start_pasuk: 14, end_perek: 13, end_pasuk: 4 )
Aliya.create(aliyah_number: 3, parsha_id: לך_לך.id, start_perek: 13,start_pasuk: 5, end_perek: 13, end_pasuk: 18 )
Aliya.create(aliyah_number: 4, parsha_id: לך_לך.id, start_perek: 14,start_pasuk: 1, end_perek: 14, end_pasuk: 20 )
Aliya.create(aliyah_number: 5, parsha_id: לך_לך.id, start_perek: 14,start_pasuk: 21, end_perek: 15, end_pasuk: 6 )
Aliya.create(aliyah_number: 6, parsha_id: לך_לך.id, start_perek: 15,start_pasuk: 7, end_perek: 17, end_pasuk: 6 )
Aliya.create(aliyah_number: 7, parsha_id: לך_לך.id, start_perek: 17,start_pasuk: 7, end_perek: 17, end_pasuk: 27 )
Aliya.create(aliyah_number: 8, parsha_id: לך_לך.id, start_perek: 17,start_pasuk: 24, end_perek: 17, end_pasuk: 27 )
Aliya.create(aliyah_number: 1, parsha_id: וירא.id, start_perek: 18,start_pasuk: 1, end_perek: 18, end_pasuk: 14 )
Aliya.create(aliyah_number: 2, parsha_id: וירא.id, start_perek: 18,start_pasuk: 15, end_perek: 18, end_pasuk: 33 )
Aliya.create(aliyah_number: 3, parsha_id: וירא.id, start_perek: 19,start_pasuk: 1, end_perek: 19, end_pasuk: 20 )
Aliya.create(aliyah_number: 4, parsha_id: וירא.id, start_perek: 19,start_pasuk: 21, end_perek: 21, end_pasuk: 4 )
Aliya.create(aliyah_number: 5, parsha_id: וירא.id, start_perek: 21,start_pasuk: 5, end_perek: 21, end_pasuk: 21 )
Aliya.create(aliyah_number: 6, parsha_id: וירא.id, start_perek: 21,start_pasuk: 22, end_perek: 21, end_pasuk: 34 )
Aliya.create(aliyah_number: 7, parsha_id: וירא.id, start_perek: 22,start_pasuk: 1, end_perek: 22, end_pasuk: 24 )
Aliya.create(aliyah_number: 8, parsha_id: וירא.id, start_perek: 22,start_pasuk: 20, end_perek: 22, end_pasuk: 24 )
Aliya.create(aliyah_number: 1, parsha_id: חיי_שרה.id, start_perek: 23,start_pasuk: 1, end_perek: 23, end_pasuk: 16 )
Aliya.create(aliyah_number: 2, parsha_id: חיי_שרה.id, start_perek: 23,start_pasuk: 17, end_perek: 24, end_pasuk: 9 )
Aliya.create(aliyah_number: 3, parsha_id: חיי_שרה.id, start_perek: 24,start_pasuk: 10, end_perek: 24, end_pasuk: 26 )
Aliya.create(aliyah_number: 4, parsha_id: חיי_שרה.id, start_perek: 24,start_pasuk: 27, end_perek: 24, end_pasuk: 52 )
Aliya.create(aliyah_number: 5, parsha_id: חיי_שרה.id, start_perek: 24,start_pasuk: 53, end_perek: 24, end_pasuk: 67 )
Aliya.create(aliyah_number: 6, parsha_id: חיי_שרה.id, start_perek: 25,start_pasuk: 1, end_perek: 25, end_pasuk: 11 )
Aliya.create(aliyah_number: 7, parsha_id: חיי_שרה.id, start_perek: 25,start_pasuk: 12, end_perek: 25, end_pasuk: 18 )
Aliya.create(aliyah_number: 8, parsha_id: חיי_שרה.id, start_perek: 25,start_pasuk: 16, end_perek: 25, end_pasuk: 18 )
Aliya.create(aliyah_number: 1, parsha_id: תולדות.id, start_perek: 25,start_pasuk: 19, end_perek: 26, end_pasuk: 5 )
Aliya.create(aliyah_number: 2, parsha_id: תולדות.id, start_perek: 26,start_pasuk: 6, end_perek: 26, end_pasuk: 12 )
Aliya.create(aliyah_number: 3, parsha_id: תולדות.id, start_perek: 26,start_pasuk: 13, end_perek: 26, end_pasuk: 22 )
Aliya.create(aliyah_number: 4, parsha_id: תולדות.id, start_perek: 26,start_pasuk: 23, end_perek: 26, end_pasuk: 29 )
Aliya.create(aliyah_number: 5, parsha_id: תולדות.id, start_perek: 26,start_pasuk: 30, end_perek: 27, end_pasuk: 27 )
Aliya.create(aliyah_number: 6, parsha_id: תולדות.id, start_perek: 27,start_pasuk: 28, end_perek: 28, end_pasuk: 4 )
Aliya.create(aliyah_number: 7, parsha_id: תולדות.id, start_perek: 28,start_pasuk: 5, end_perek: 28, end_pasuk: 9 )
Aliya.create(aliyah_number: 8, parsha_id: תולדות.id, start_perek: 28,start_pasuk: 7, end_perek: 28, end_pasuk: 9 )
Aliya.create(aliyah_number: 1, parsha_id: ויצא.id, start_perek: 28,start_pasuk: 10, end_perek: 28, end_pasuk: 22 )
Aliya.create(aliyah_number: 2, parsha_id: ויצא.id, start_perek: 29,start_pasuk: 1, end_perek: 29, end_pasuk: 17 )
Aliya.create(aliyah_number: 3, parsha_id: ויצא.id, start_perek: 29,start_pasuk: 18, end_perek: 30, end_pasuk: 13 )
Aliya.create(aliyah_number: 4, parsha_id: ויצא.id, start_perek: 30,start_pasuk: 14, end_perek: 30, end_pasuk: 27 )
Aliya.create(aliyah_number: 5, parsha_id: ויצא.id, start_perek: 30,start_pasuk: 28, end_perek: 31, end_pasuk: 16 )
Aliya.create(aliyah_number: 6, parsha_id: ויצא.id, start_perek: 31,start_pasuk: 17, end_perek: 31, end_pasuk: 42 )
Aliya.create(aliyah_number: 7, parsha_id: ויצא.id, start_perek: 31,start_pasuk: 43, end_perek: 32, end_pasuk: 3 )
Aliya.create(aliyah_number: 8, parsha_id: ויצא.id, start_perek: 32,start_pasuk: 1, end_perek: 32, end_pasuk: 3 )
Aliya.create(aliyah_number: 1, parsha_id: וישלח.id, start_perek: 32,start_pasuk: 4, end_perek: 32, end_pasuk: 13 )
Aliya.create(aliyah_number: 2, parsha_id: וישלח.id, start_perek: 32,start_pasuk: 14, end_perek: 32, end_pasuk: 30 )
Aliya.create(aliyah_number: 3, parsha_id: וישלח.id, start_perek: 32,start_pasuk: 31, end_perek: 33, end_pasuk: 5 )
Aliya.create(aliyah_number: 4, parsha_id: וישלח.id, start_perek: 33,start_pasuk: 6, end_perek: 33, end_pasuk: 20 )
Aliya.create(aliyah_number: 5, parsha_id: וישלח.id, start_perek: 34,start_pasuk: 1, end_perek: 35, end_pasuk: 11 )
Aliya.create(aliyah_number: 6, parsha_id: וישלח.id, start_perek: 35,start_pasuk: 12, end_perek: 36, end_pasuk: 19 )
Aliya.create(aliyah_number: 7, parsha_id: וישלח.id, start_perek: 36,start_pasuk: 20, end_perek: 36, end_pasuk: 43 )
Aliya.create(aliyah_number: 8, parsha_id: וישלח.id, start_perek: 36,start_pasuk: 40, end_perek: 36, end_pasuk: 43 )
Aliya.create(aliyah_number: 1, parsha_id: וישב.id, start_perek: 37,start_pasuk: 1, end_perek: 37, end_pasuk: 11 )
Aliya.create(aliyah_number: 2, parsha_id: וישב.id, start_perek: 37,start_pasuk: 12, end_perek: 37, end_pasuk: 22 )
Aliya.create(aliyah_number: 3, parsha_id: וישב.id, start_perek: 37,start_pasuk: 23, end_perek: 37, end_pasuk: 36 )
Aliya.create(aliyah_number: 4, parsha_id: וישב.id, start_perek: 38,start_pasuk: 1, end_perek: 38, end_pasuk: 30 )
Aliya.create(aliyah_number: 5, parsha_id: וישב.id, start_perek: 39,start_pasuk: 1, end_perek: 39, end_pasuk: 6 )
Aliya.create(aliyah_number: 6, parsha_id: וישב.id, start_perek: 39,start_pasuk: 7, end_perek: 39, end_pasuk: 23 )
Aliya.create(aliyah_number: 7, parsha_id: וישב.id, start_perek: 40,start_pasuk: 1, end_perek: 40, end_pasuk: 23 )
Aliya.create(aliyah_number: 8, parsha_id: וישב.id, start_perek: 40,start_pasuk: 20, end_perek: 40, end_pasuk: 23 )
Aliya.create(aliyah_number: 1, parsha_id: מקץ.id, start_perek: 41,start_pasuk: 1, end_perek: 41, end_pasuk: 14 )
Aliya.create(aliyah_number: 2, parsha_id: מקץ.id, start_perek: 41,start_pasuk: 15, end_perek: 41, end_pasuk: 38 )
Aliya.create(aliyah_number: 3, parsha_id: מקץ.id, start_perek: 41,start_pasuk: 39, end_perek: 41, end_pasuk: 52 )
Aliya.create(aliyah_number: 4, parsha_id: מקץ.id, start_perek: 41,start_pasuk: 53, end_perek: 42, end_pasuk: 18 )
Aliya.create(aliyah_number: 5, parsha_id: מקץ.id, start_perek: 42,start_pasuk: 19, end_perek: 43, end_pasuk: 15 )
Aliya.create(aliyah_number: 6, parsha_id: מקץ.id, start_perek: 43,start_pasuk: 16, end_perek: 43, end_pasuk: 29 )
Aliya.create(aliyah_number: 7, parsha_id: מקץ.id, start_perek: 43,start_pasuk: 30, end_perek: 44, end_pasuk: 17 )
Aliya.create(aliyah_number: 8, parsha_id: מקץ.id, start_perek: 44,start_pasuk: 14, end_perek: 44, end_pasuk: 17 )
Aliya.create(aliyah_number: 1, parsha_id: ויגש.id, start_perek: 44,start_pasuk: 18, end_perek: 44, end_pasuk: 30 )
Aliya.create(aliyah_number: 2, parsha_id: ויגש.id, start_perek: 44,start_pasuk: 31, end_perek: 45, end_pasuk: 7 )
Aliya.create(aliyah_number: 3, parsha_id: ויגש.id, start_perek: 45,start_pasuk: 8, end_perek: 45, end_pasuk: 18 )
Aliya.create(aliyah_number: 4, parsha_id: ויגש.id, start_perek: 45,start_pasuk: 19, end_perek: 45, end_pasuk: 27 )
Aliya.create(aliyah_number: 5, parsha_id: ויגש.id, start_perek: 45,start_pasuk: 28, end_perek: 46, end_pasuk: 27 )
Aliya.create(aliyah_number: 6, parsha_id: ויגש.id, start_perek: 46,start_pasuk: 28, end_perek: 47, end_pasuk: 10 )
Aliya.create(aliyah_number: 7, parsha_id: ויגש.id, start_perek: 47,start_pasuk: 11, end_perek: 47, end_pasuk: 27 )
Aliya.create(aliyah_number: 8, parsha_id: ויגש.id, start_perek: 47,start_pasuk: 25, end_perek: 47, end_pasuk: 27 )
Aliya.create(aliyah_number: 1, parsha_id: ויחי.id, start_perek: 47,start_pasuk: 28, end_perek: 48, end_pasuk: 9 )
Aliya.create(aliyah_number: 2, parsha_id: ויחי.id, start_perek: 48,start_pasuk: 10, end_perek: 48, end_pasuk: 16 )
Aliya.create(aliyah_number: 3, parsha_id: ויחי.id, start_perek: 48,start_pasuk: 17, end_perek: 48, end_pasuk: 22 )
Aliya.create(aliyah_number: 4, parsha_id: ויחי.id, start_perek: 49,start_pasuk: 1, end_perek: 49, end_pasuk: 18 )
Aliya.create(aliyah_number: 5, parsha_id: ויחי.id, start_perek: 49,start_pasuk: 19, end_perek: 49, end_pasuk: 26 )
Aliya.create(aliyah_number: 6, parsha_id: ויחי.id, start_perek: 49,start_pasuk: 27, end_perek: 50, end_pasuk: 20 )
Aliya.create(aliyah_number: 7, parsha_id: ויחי.id, start_perek: 50,start_pasuk: 21, end_perek: 50, end_pasuk: 26 )
Aliya.create(aliyah_number: 8, parsha_id: ויחי.id, start_perek: 50,start_pasuk: 23, end_perek: 50, end_pasuk: 26 )
Aliya.create(aliyah_number: 1, parsha_id: שמות.id, start_perek: 1,start_pasuk: 1, end_perek: 1, end_pasuk: 17 )
Aliya.create(aliyah_number: 2, parsha_id: שמות.id, start_perek: 1,start_pasuk: 18, end_perek: 2, end_pasuk: 10 )
Aliya.create(aliyah_number: 3, parsha_id: שמות.id, start_perek: 2,start_pasuk: 11, end_perek: 2, end_pasuk: 25 )
Aliya.create(aliyah_number: 4, parsha_id: שמות.id, start_perek: 3,start_pasuk: 1, end_perek: 3, end_pasuk: 15 )
Aliya.create(aliyah_number: 5, parsha_id: שמות.id, start_perek: 3,start_pasuk: 16, end_perek: 4, end_pasuk: 17 )
Aliya.create(aliyah_number: 6, parsha_id: שמות.id, start_perek: 4,start_pasuk: 18, end_perek: 4, end_pasuk: 31 )
Aliya.create(aliyah_number: 7, parsha_id: שמות.id, start_perek: 5,start_pasuk: 1, end_perek: 6, end_pasuk: 1 )
Aliya.create(aliyah_number: 8, parsha_id: שמות.id, start_perek: 5,start_pasuk: 22, end_perek: 6, end_pasuk: 1 )
Aliya.create(aliyah_number: 1, parsha_id: וארא.id, start_perek: 6,start_pasuk: 2, end_perek: 6, end_pasuk: 13 )
Aliya.create(aliyah_number: 2, parsha_id: וארא.id, start_perek: 6,start_pasuk: 14, end_perek: 6, end_pasuk: 28 )
Aliya.create(aliyah_number: 3, parsha_id: וארא.id, start_perek: 6,start_pasuk: 29, end_perek: 7, end_pasuk: 7 )
Aliya.create(aliyah_number: 4, parsha_id: וארא.id, start_perek: 7,start_pasuk: 8, end_perek: 8, end_pasuk: 6 )
Aliya.create(aliyah_number: 5, parsha_id: וארא.id, start_perek: 8,start_pasuk: 7, end_perek: 8, end_pasuk: 18 )
Aliya.create(aliyah_number: 6, parsha_id: וארא.id, start_perek: 8,start_pasuk: 19, end_perek: 9, end_pasuk: 16 )
Aliya.create(aliyah_number: 7, parsha_id: וארא.id, start_perek: 9,start_pasuk: 17, end_perek: 9, end_pasuk: 35 )
Aliya.create(aliyah_number: 8, parsha_id: וארא.id, start_perek: 9,start_pasuk: 33, end_perek: 9, end_pasuk: 35 )
Aliya.create(aliyah_number: 1, parsha_id: בא.id, start_perek: 10,start_pasuk: 1, end_perek: 10, end_pasuk: 11 )
Aliya.create(aliyah_number: 2, parsha_id: בא.id, start_perek: 10,start_pasuk: 12, end_perek: 10, end_pasuk: 23 )
Aliya.create(aliyah_number: 3, parsha_id: בא.id, start_perek: 10,start_pasuk: 24, end_perek: 11, end_pasuk: 3 )
Aliya.create(aliyah_number: 4, parsha_id: בא.id, start_perek: 11,start_pasuk: 4, end_perek: 12, end_pasuk: 20 )
Aliya.create(aliyah_number: 5, parsha_id: בא.id, start_perek: 12,start_pasuk: 21, end_perek: 12, end_pasuk: 28 )
Aliya.create(aliyah_number: 6, parsha_id: בא.id, start_perek: 12,start_pasuk: 29, end_perek: 12, end_pasuk: 51 )
Aliya.create(aliyah_number: 7, parsha_id: בא.id, start_perek: 13,start_pasuk: 1, end_perek: 13, end_pasuk: 16 )
Aliya.create(aliyah_number: 8, parsha_id: בא.id, start_perek: 13,start_pasuk: 14, end_perek: 13, end_pasuk: 16 )
Aliya.create(aliyah_number: 1, parsha_id: בשלח.id, start_perek: 13,start_pasuk: 17, end_perek: 14, end_pasuk: 8 )
Aliya.create(aliyah_number: 2, parsha_id: בשלח.id, start_perek: 14,start_pasuk: 9, end_perek: 14, end_pasuk: 14 )
Aliya.create(aliyah_number: 3, parsha_id: בשלח.id, start_perek: 14,start_pasuk: 15, end_perek: 14, end_pasuk: 25 )
Aliya.create(aliyah_number: 4, parsha_id: בשלח.id, start_perek: 14,start_pasuk: 26, end_perek: 15, end_pasuk: 26 )
Aliya.create(aliyah_number: 5, parsha_id: בשלח.id, start_perek: 15,start_pasuk: 27, end_perek: 16, end_pasuk: 10 )
Aliya.create(aliyah_number: 6, parsha_id: בשלח.id, start_perek: 16,start_pasuk: 11, end_perek: 16, end_pasuk: 36 )
Aliya.create(aliyah_number: 7, parsha_id: בשלח.id, start_perek: 17,start_pasuk: 1, end_perek: 17, end_pasuk: 16 )
Aliya.create(aliyah_number: 8, parsha_id: בשלח.id, start_perek: 17,start_pasuk: 14, end_perek: 17, end_pasuk: 16 )
Aliya.create(aliyah_number: 1, parsha_id: יתרו.id, start_perek: 18,start_pasuk: 1, end_perek: 18, end_pasuk: 12 )
Aliya.create(aliyah_number: 2, parsha_id: יתרו.id, start_perek: 18,start_pasuk: 13, end_perek: 18, end_pasuk: 23 )
Aliya.create(aliyah_number: 3, parsha_id: יתרו.id, start_perek: 18,start_pasuk: 24, end_perek: 18, end_pasuk: 27 )
Aliya.create(aliyah_number: 4, parsha_id: יתרו.id, start_perek: 19,start_pasuk: 1, end_perek: 19, end_pasuk: 6 )
Aliya.create(aliyah_number: 5, parsha_id: יתרו.id, start_perek: 19,start_pasuk: 7, end_perek: 19, end_pasuk: 19 )
Aliya.create(aliyah_number: 6, parsha_id: יתרו.id, start_perek: 19,start_pasuk: 20, end_perek: 20, end_pasuk: 14 )
Aliya.create(aliyah_number: 7, parsha_id: יתרו.id, start_perek: 20,start_pasuk: 15, end_perek: 20, end_pasuk: 23 )
Aliya.create(aliyah_number: 8, parsha_id: יתרו.id, start_perek: 20,start_pasuk: 19, end_perek: 20, end_pasuk: 23 )
Aliya.create(aliyah_number: 1, parsha_id: משפטים.id, start_perek: 21,start_pasuk: 1, end_perek: 21, end_pasuk: 19 )
Aliya.create(aliyah_number: 2, parsha_id: משפטים.id, start_perek: 21,start_pasuk: 20, end_perek: 22, end_pasuk: 3 )
Aliya.create(aliyah_number: 3, parsha_id: משפטים.id, start_perek: 22,start_pasuk: 4, end_perek: 22, end_pasuk: 26 )
Aliya.create(aliyah_number: 4, parsha_id: משפטים.id, start_perek: 22,start_pasuk: 27, end_perek: 23, end_pasuk: 5 )
Aliya.create(aliyah_number: 5, parsha_id: משפטים.id, start_perek: 23,start_pasuk: 6, end_perek: 23, end_pasuk: 19 )
Aliya.create(aliyah_number: 6, parsha_id: משפטים.id, start_perek: 23,start_pasuk: 20, end_perek: 23, end_pasuk: 25 )
Aliya.create(aliyah_number: 7, parsha_id: משפטים.id, start_perek: 23,start_pasuk: 26, end_perek: 24, end_pasuk: 18 )
Aliya.create(aliyah_number: 8, parsha_id: משפטים.id, start_perek: 24,start_pasuk: 15, end_perek: 24, end_pasuk: 18 )
Aliya.create(aliyah_number: 1, parsha_id: תרומה.id, start_perek: 25,start_pasuk: 1, end_perek: 25, end_pasuk: 16 )
Aliya.create(aliyah_number: 2, parsha_id: תרומה.id, start_perek: 25,start_pasuk: 17, end_perek: 25, end_pasuk: 30 )
Aliya.create(aliyah_number: 3, parsha_id: תרומה.id, start_perek: 25,start_pasuk: 31, end_perek: 26, end_pasuk: 14 )
Aliya.create(aliyah_number: 4, parsha_id: תרומה.id, start_perek: 26,start_pasuk: 15, end_perek: 26, end_pasuk: 30 )
Aliya.create(aliyah_number: 5, parsha_id: תרומה.id, start_perek: 26,start_pasuk: 31, end_perek: 26, end_pasuk: 37 )
Aliya.create(aliyah_number: 6, parsha_id: תרומה.id, start_perek: 27,start_pasuk: 1, end_perek: 27, end_pasuk: 8 )
Aliya.create(aliyah_number: 7, parsha_id: תרומה.id, start_perek: 27,start_pasuk: 9, end_perek: 27, end_pasuk: 19 )
Aliya.create(aliyah_number: 8, parsha_id: תרומה.id, start_perek: 27,start_pasuk: 17, end_perek: 27, end_pasuk: 19 )
Aliya.create(aliyah_number: 1, parsha_id: תצוה.id, start_perek: 27,start_pasuk: 20, end_perek: 28, end_pasuk: 12 )
Aliya.create(aliyah_number: 2, parsha_id: תצוה.id, start_perek: 28,start_pasuk: 13, end_perek: 28, end_pasuk: 30 )
Aliya.create(aliyah_number: 3, parsha_id: תצוה.id, start_perek: 28,start_pasuk: 31, end_perek: 28, end_pasuk: 43 )
Aliya.create(aliyah_number: 4, parsha_id: תצוה.id, start_perek: 29,start_pasuk: 1, end_perek: 29, end_pasuk: 18 )
Aliya.create(aliyah_number: 5, parsha_id: תצוה.id, start_perek: 29,start_pasuk: 19, end_perek: 29, end_pasuk: 37 )
Aliya.create(aliyah_number: 6, parsha_id: תצוה.id, start_perek: 29,start_pasuk: 38, end_perek: 29, end_pasuk: 46 )
Aliya.create(aliyah_number: 7, parsha_id: תצוה.id, start_perek: 30,start_pasuk: 1, end_perek: 30, end_pasuk: 10 )
Aliya.create(aliyah_number: 8, parsha_id: תצוה.id, start_perek: 30,start_pasuk: 8, end_perek: 30, end_pasuk: 10 )
Aliya.create(aliyah_number: 1, parsha_id: כי_תשא.id, start_perek: 30,start_pasuk: 11, end_perek: 31, end_pasuk: 17 )
Aliya.create(aliyah_number: 2, parsha_id: כי_תשא.id, start_perek: 31,start_pasuk: 18, end_perek: 33, end_pasuk: 11 )
Aliya.create(aliyah_number: 3, parsha_id: כי_תשא.id, start_perek: 33,start_pasuk: 12, end_perek: 33, end_pasuk: 16 )
Aliya.create(aliyah_number: 4, parsha_id: כי_תשא.id, start_perek: 33,start_pasuk: 17, end_perek: 33, end_pasuk: 23 )
Aliya.create(aliyah_number: 5, parsha_id: כי_תשא.id, start_perek: 34,start_pasuk: 1, end_perek: 34, end_pasuk: 9 )
Aliya.create(aliyah_number: 6, parsha_id: כי_תשא.id, start_perek: 34,start_pasuk: 10, end_perek: 34, end_pasuk: 26 )
Aliya.create(aliyah_number: 7, parsha_id: כי_תשא.id, start_perek: 34,start_pasuk: 27, end_perek: 34, end_pasuk: 35 )
Aliya.create(aliyah_number: 8, parsha_id: כי_תשא.id, start_perek: 34,start_pasuk: 33, end_perek: 34, end_pasuk: 35 )
Aliya.create(aliyah_number: 1, parsha_id: ויקהל.id, start_perek: 35,start_pasuk: 1, end_perek: 35, end_pasuk: 20 )
Aliya.create(aliyah_number: 2, parsha_id: ויקהל.id, start_perek: 35,start_pasuk: 21, end_perek: 35, end_pasuk: 29 )
Aliya.create(aliyah_number: 3, parsha_id: ויקהל.id, start_perek: 35,start_pasuk: 30, end_perek: 36, end_pasuk: 7 )
Aliya.create(aliyah_number: 4, parsha_id: ויקהל.id, start_perek: 36,start_pasuk: 8, end_perek: 36, end_pasuk: 19 )
Aliya.create(aliyah_number: 5, parsha_id: ויקהל.id, start_perek: 36,start_pasuk: 20, end_perek: 37, end_pasuk: 16 )
Aliya.create(aliyah_number: 6, parsha_id: ויקהל.id, start_perek: 37,start_pasuk: 17, end_perek: 37, end_pasuk: 29 )
Aliya.create(aliyah_number: 7, parsha_id: ויקהל.id, start_perek: 38,start_pasuk: 1, end_perek: 38, end_pasuk: 20 )
Aliya.create(aliyah_number: 8, parsha_id: ויקהל.id, start_perek: 38,start_pasuk: 18, end_perek: 38, end_pasuk: 20 )
Aliya.create(aliyah_number: 1, parsha_id: פקודי.id, start_perek: 38,start_pasuk: 21, end_perek: 39, end_pasuk: 1 )
Aliya.create(aliyah_number: 2, parsha_id: פקודי.id, start_perek: 39,start_pasuk: 2, end_perek: 39, end_pasuk: 21 )
Aliya.create(aliyah_number: 3, parsha_id: פקודי.id, start_perek: 39,start_pasuk: 22, end_perek: 39, end_pasuk: 32 )
Aliya.create(aliyah_number: 4, parsha_id: פקודי.id, start_perek: 39,start_pasuk: 33, end_perek: 39, end_pasuk: 43 )
Aliya.create(aliyah_number: 5, parsha_id: פקודי.id, start_perek: 40,start_pasuk: 1, end_perek: 40, end_pasuk: 16 )
Aliya.create(aliyah_number: 6, parsha_id: פקודי.id, start_perek: 40,start_pasuk: 17, end_perek: 40, end_pasuk: 27 )
Aliya.create(aliyah_number: 7, parsha_id: פקודי.id, start_perek: 40,start_pasuk: 28, end_perek: 40, end_pasuk: 38 )
Aliya.create(aliyah_number: 8, parsha_id: פקודי.id, start_perek: 40,start_pasuk: 34, end_perek: 40, end_pasuk: 38 )
Aliya.create(aliyah_number: 1, parsha_id: ויקהל_פקודי.id, start_perek: 35,start_pasuk: 1, end_perek: 35, end_pasuk: 29 )
Aliya.create(aliyah_number: 2, parsha_id: ויקהל_פקודי.id, start_perek: 35,start_pasuk: 30, end_perek: 37, end_pasuk: 16 )
Aliya.create(aliyah_number: 3, parsha_id: ויקהל_פקודי.id, start_perek: 37,start_pasuk: 17, end_perek: 37, end_pasuk: 29 )
Aliya.create(aliyah_number: 4, parsha_id: ויקהל_פקודי.id, start_perek: 38,start_pasuk: 1, end_perek: 39, end_pasuk: 1 )
Aliya.create(aliyah_number: 5, parsha_id: ויקהל_פקודי.id, start_perek: 39,start_pasuk: 2, end_perek: 39, end_pasuk: 21 )
Aliya.create(aliyah_number: 6, parsha_id: ויקהל_פקודי.id, start_perek: 39,start_pasuk: 22, end_perek: 39, end_pasuk: 43 )
Aliya.create(aliyah_number: 7, parsha_id: ויקהל_פקודי.id, start_perek: 40,start_pasuk: 1, end_perek: 40, end_pasuk: 38 )
Aliya.create(aliyah_number: 8, parsha_id: ויקהל_פקודי.id, start_perek: 40,start_pasuk: 34, end_perek: 40, end_pasuk: 38 )
Aliya.create(aliyah_number: 1, parsha_id: ויקרא.id, start_perek: 1,start_pasuk: 1, end_perek: 1, end_pasuk: 13 )
Aliya.create(aliyah_number: 2, parsha_id: ויקרא.id, start_perek: 1,start_pasuk: 14, end_perek: 2, end_pasuk: 6 )
Aliya.create(aliyah_number: 3, parsha_id: ויקרא.id, start_perek: 2,start_pasuk: 7, end_perek: 2, end_pasuk: 16 )
Aliya.create(aliyah_number: 4, parsha_id: ויקרא.id, start_perek: 3,start_pasuk: 1, end_perek: 3, end_pasuk: 17 )
Aliya.create(aliyah_number: 5, parsha_id: ויקרא.id, start_perek: 4,start_pasuk: 1, end_perek: 4, end_pasuk: 26 )
Aliya.create(aliyah_number: 6, parsha_id: ויקרא.id, start_perek: 4,start_pasuk: 27, end_perek: 5, end_pasuk: 10 )
Aliya.create(aliyah_number: 7, parsha_id: ויקרא.id, start_perek: 5,start_pasuk: 11, end_perek: 5, end_pasuk: 26 )
Aliya.create(aliyah_number: 8, parsha_id: ויקרא.id, start_perek: 5,start_pasuk: 24, end_perek: 5, end_pasuk: 26 )
Aliya.create(aliyah_number: 1, parsha_id: צו.id, start_perek: 6,start_pasuk: 1, end_perek: 6, end_pasuk: 11 )
Aliya.create(aliyah_number: 2, parsha_id: צו.id, start_perek: 6,start_pasuk: 12, end_perek: 7, end_pasuk: 10 )
Aliya.create(aliyah_number: 3, parsha_id: צו.id, start_perek: 7,start_pasuk: 11, end_perek: 7, end_pasuk: 38 )
Aliya.create(aliyah_number: 4, parsha_id: צו.id, start_perek: 8,start_pasuk: 1, end_perek: 8, end_pasuk: 13 )
Aliya.create(aliyah_number: 5, parsha_id: צו.id, start_perek: 8,start_pasuk: 14, end_perek: 8, end_pasuk: 21 )
Aliya.create(aliyah_number: 6, parsha_id: צו.id, start_perek: 8,start_pasuk: 22, end_perek: 8, end_pasuk: 29 )
Aliya.create(aliyah_number: 7, parsha_id: צו.id, start_perek: 8,start_pasuk: 30, end_perek: 8, end_pasuk: 36 )
Aliya.create(aliyah_number: 8, parsha_id: צו.id, start_perek: 8,start_pasuk: 33, end_perek: 8, end_pasuk: 36 )
Aliya.create(aliyah_number: 1, parsha_id: שמיני.id, start_perek: 9,start_pasuk: 1, end_perek: 9, end_pasuk: 16 )
Aliya.create(aliyah_number: 2, parsha_id: שמיני.id, start_perek: 9,start_pasuk: 17, end_perek: 9, end_pasuk: 23 )
Aliya.create(aliyah_number: 3, parsha_id: שמיני.id, start_perek: 9,start_pasuk: 24, end_perek: 10, end_pasuk: 11 )
Aliya.create(aliyah_number: 4, parsha_id: שמיני.id, start_perek: 10,start_pasuk: 12, end_perek: 10, end_pasuk: 15 )
Aliya.create(aliyah_number: 5, parsha_id: שמיני.id, start_perek: 10,start_pasuk: 16, end_perek: 10, end_pasuk: 20 )
Aliya.create(aliyah_number: 6, parsha_id: שמיני.id, start_perek: 11,start_pasuk: 1, end_perek: 11, end_pasuk: 32 )
Aliya.create(aliyah_number: 7, parsha_id: שמיני.id, start_perek: 11,start_pasuk: 33, end_perek: 11, end_pasuk: 47 )
Aliya.create(aliyah_number: 8, parsha_id: שמיני.id, start_perek: 11,start_pasuk: 45, end_perek: 11, end_pasuk: 47 )
Aliya.create(aliyah_number: 1, parsha_id: תזריע.id, start_perek: 12,start_pasuk: 1, end_perek: 13, end_pasuk: 5 )
Aliya.create(aliyah_number: 2, parsha_id: תזריע.id, start_perek: 13,start_pasuk: 6, end_perek: 13, end_pasuk: 17 )
Aliya.create(aliyah_number: 3, parsha_id: תזריע.id, start_perek: 13,start_pasuk: 18, end_perek: 13, end_pasuk: 23 )
Aliya.create(aliyah_number: 4, parsha_id: תזריע.id, start_perek: 13,start_pasuk: 24, end_perek: 13, end_pasuk: 28 )
Aliya.create(aliyah_number: 5, parsha_id: תזריע.id, start_perek: 13,start_pasuk: 29, end_perek: 13, end_pasuk: 39 )
Aliya.create(aliyah_number: 6, parsha_id: תזריע.id, start_perek: 13,start_pasuk: 40, end_perek: 13, end_pasuk: 54 )
Aliya.create(aliyah_number: 7, parsha_id: תזריע.id, start_perek: 13,start_pasuk: 55, end_perek: 13, end_pasuk: 59 )
Aliya.create(aliyah_number: 8, parsha_id: תזריע.id, start_perek: 13,start_pasuk: 57, end_perek: 13, end_pasuk: 59 )
Aliya.create(aliyah_number: 1, parsha_id: מצורע.id, start_perek: 14,start_pasuk: 1, end_perek: 14, end_pasuk: 12 )
Aliya.create(aliyah_number: 2, parsha_id: מצורע.id, start_perek: 14,start_pasuk: 13, end_perek: 14, end_pasuk: 20 )
Aliya.create(aliyah_number: 3, parsha_id: מצורע.id, start_perek: 14,start_pasuk: 21, end_perek: 14, end_pasuk: 32 )
Aliya.create(aliyah_number: 4, parsha_id: מצורע.id, start_perek: 14,start_pasuk: 33, end_perek: 14, end_pasuk: 53 )
Aliya.create(aliyah_number: 5, parsha_id: מצורע.id, start_perek: 14,start_pasuk: 54, end_perek: 15, end_pasuk: 15 )
Aliya.create(aliyah_number: 6, parsha_id: מצורע.id, start_perek: 15,start_pasuk: 16, end_perek: 15, end_pasuk: 28 )
Aliya.create(aliyah_number: 7, parsha_id: מצורע.id, start_perek: 15,start_pasuk: 29, end_perek: 15, end_pasuk: 33 )
Aliya.create(aliyah_number: 8, parsha_id: מצורע.id, start_perek: 15,start_pasuk: 31, end_perek: 15, end_pasuk: 33 )
Aliya.create(aliyah_number: 1, parsha_id: תזריע_מצורע.id, start_perek: 12,start_pasuk: 1, end_perek: 13, end_pasuk: 23 )
Aliya.create(aliyah_number: 2, parsha_id: תזריע_מצורע.id, start_perek: 13,start_pasuk: 24, end_perek: 13, end_pasuk: 39 )
Aliya.create(aliyah_number: 3, parsha_id: תזריע_מצורע.id, start_perek: 13,start_pasuk: 40, end_perek: 13, end_pasuk: 54 )
Aliya.create(aliyah_number: 4, parsha_id: תזריע_מצורע.id, start_perek: 13,start_pasuk: 55, end_perek: 14, end_pasuk: 20 )
Aliya.create(aliyah_number: 5, parsha_id: תזריע_מצורע.id, start_perek: 14,start_pasuk: 21, end_perek: 14, end_pasuk: 32 )
Aliya.create(aliyah_number: 6, parsha_id: תזריע_מצורע.id, start_perek: 14,start_pasuk: 33, end_perek: 15, end_pasuk: 15 )
Aliya.create(aliyah_number: 7, parsha_id: תזריע_מצורע.id, start_perek: 15,start_pasuk: 16, end_perek: 15, end_pasuk: 33 )
Aliya.create(aliyah_number: 8, parsha_id: תזריע_מצורע.id, start_perek: 15,start_pasuk: 31, end_perek: 15, end_pasuk: 33 )
Aliya.create(aliyah_number: 1, parsha_id: אחרי_מות.id, start_perek: 16,start_pasuk: 1, end_perek: 16, end_pasuk: 17 )
Aliya.create(aliyah_number: 2, parsha_id: אחרי_מות.id, start_perek: 16,start_pasuk: 18, end_perek: 16, end_pasuk: 24 )
Aliya.create(aliyah_number: 3, parsha_id: אחרי_מות.id, start_perek: 16,start_pasuk: 25, end_perek: 16, end_pasuk: 34 )
Aliya.create(aliyah_number: 4, parsha_id: אחרי_מות.id, start_perek: 17,start_pasuk: 1, end_perek: 17, end_pasuk: 7 )
Aliya.create(aliyah_number: 5, parsha_id: אחרי_מות.id, start_perek: 17,start_pasuk: 8, end_perek: 18, end_pasuk: 5 )
Aliya.create(aliyah_number: 6, parsha_id: אחרי_מות.id, start_perek: 18,start_pasuk: 6, end_perek: 18, end_pasuk: 21 )
Aliya.create(aliyah_number: 7, parsha_id: אחרי_מות.id, start_perek: 18,start_pasuk: 22, end_perek: 18, end_pasuk: 30 )
Aliya.create(aliyah_number: 8, parsha_id: אחרי_מות.id, start_perek: 18,start_pasuk: 28, end_perek: 18, end_pasuk: 30 )
Aliya.create(aliyah_number: 1, parsha_id: קדושים.id, start_perek: 19,start_pasuk: 1, end_perek: 19, end_pasuk: 14 )
Aliya.create(aliyah_number: 2, parsha_id: קדושים.id, start_perek: 19,start_pasuk: 15, end_perek: 19, end_pasuk: 22 )
Aliya.create(aliyah_number: 3, parsha_id: קדושים.id, start_perek: 19,start_pasuk: 23, end_perek: 19, end_pasuk: 32 )
Aliya.create(aliyah_number: 4, parsha_id: קדושים.id, start_perek: 19,start_pasuk: 33, end_perek: 19, end_pasuk: 37 )
Aliya.create(aliyah_number: 5, parsha_id: קדושים.id, start_perek: 20,start_pasuk: 1, end_perek: 20, end_pasuk: 7 )
Aliya.create(aliyah_number: 6, parsha_id: קדושים.id, start_perek: 20,start_pasuk: 8, end_perek: 20, end_pasuk: 22 )
Aliya.create(aliyah_number: 7, parsha_id: קדושים.id, start_perek: 20,start_pasuk: 23, end_perek: 20, end_pasuk: 27 )
Aliya.create(aliyah_number: 8, parsha_id: קדושים.id, start_perek: 20,start_pasuk: 25, end_perek: 20, end_pasuk: 27 )
Aliya.create(aliyah_number: 1, parsha_id: אחרי_מות_קדושים.id, start_perek: 16,start_pasuk: 1, end_perek: 16, end_pasuk: 24 )
Aliya.create(aliyah_number: 2, parsha_id: אחרי_מות_קדושים.id, start_perek: 16,start_pasuk: 25, end_perek: 17, end_pasuk: 7 )
Aliya.create(aliyah_number: 3, parsha_id: אחרי_מות_קדושים.id, start_perek: 17,start_pasuk: 8, end_perek: 18, end_pasuk: 21 )
Aliya.create(aliyah_number: 4, parsha_id: אחרי_מות_קדושים.id, start_perek: 18,start_pasuk: 22, end_perek: 19, end_pasuk: 14 )
Aliya.create(aliyah_number: 5, parsha_id: אחרי_מות_קדושים.id, start_perek: 19,start_pasuk: 15, end_perek: 19, end_pasuk: 32 )
Aliya.create(aliyah_number: 6, parsha_id: אחרי_מות_קדושים.id, start_perek: 19,start_pasuk: 33, end_perek: 20, end_pasuk: 7 )
Aliya.create(aliyah_number: 7, parsha_id: אחרי_מות_קדושים.id, start_perek: 20,start_pasuk: 8, end_perek: 20, end_pasuk: 27 )
Aliya.create(aliyah_number: 8, parsha_id: אחרי_מות_קדושים.id, start_perek: 20,start_pasuk: 25, end_perek: 20, end_pasuk: 27 )
Aliya.create(aliyah_number: 1, parsha_id: אמור.id, start_perek: 21,start_pasuk: 1, end_perek: 21, end_pasuk: 15 )
Aliya.create(aliyah_number: 2, parsha_id: אמור.id, start_perek: 21,start_pasuk: 16, end_perek: 22, end_pasuk: 16 )
Aliya.create(aliyah_number: 3, parsha_id: אמור.id, start_perek: 22,start_pasuk: 17, end_perek: 22, end_pasuk: 33 )
Aliya.create(aliyah_number: 4, parsha_id: אמור.id, start_perek: 23,start_pasuk: 1, end_perek: 23, end_pasuk: 22 )
Aliya.create(aliyah_number: 5, parsha_id: אמור.id, start_perek: 23,start_pasuk: 23, end_perek: 23, end_pasuk: 32 )
Aliya.create(aliyah_number: 6, parsha_id: אמור.id, start_perek: 23,start_pasuk: 33, end_perek: 23, end_pasuk: 44 )
Aliya.create(aliyah_number: 7, parsha_id: אמור.id, start_perek: 24,start_pasuk: 1, end_perek: 24, end_pasuk: 23 )
Aliya.create(aliyah_number: 8, parsha_id: אמור.id, start_perek: 24,start_pasuk: 21, end_perek: 24, end_pasuk: 23 )
Aliya.create(aliyah_number: 1, parsha_id: בהר.id, start_perek: 25,start_pasuk: 1, end_perek: 25, end_pasuk: 13 )
Aliya.create(aliyah_number: 2, parsha_id: בהר.id, start_perek: 25,start_pasuk: 14, end_perek: 25, end_pasuk: 18 )
Aliya.create(aliyah_number: 3, parsha_id: בהר.id, start_perek: 25,start_pasuk: 19, end_perek: 25, end_pasuk: 24 )
Aliya.create(aliyah_number: 4, parsha_id: בהר.id, start_perek: 25,start_pasuk: 25, end_perek: 25, end_pasuk: 28 )
Aliya.create(aliyah_number: 5, parsha_id: בהר.id, start_perek: 25,start_pasuk: 29, end_perek: 25, end_pasuk: 38 )
Aliya.create(aliyah_number: 6, parsha_id: בהר.id, start_perek: 25,start_pasuk: 39, end_perek: 25, end_pasuk: 46 )
Aliya.create(aliyah_number: 7, parsha_id: בהר.id, start_perek: 25,start_pasuk: 47, end_perek: 26, end_pasuk: 2 )
Aliya.create(aliyah_number: 8, parsha_id: בהר.id, start_perek: 25,start_pasuk: 55, end_perek: 26, end_pasuk: 2 )
Aliya.create(aliyah_number: 1, parsha_id: בחקתי.id, start_perek: 26,start_pasuk: 3, end_perek: 26, end_pasuk: 5 )
Aliya.create(aliyah_number: 2, parsha_id: בחקתי.id, start_perek: 26,start_pasuk: 6, end_perek: 26, end_pasuk: 9 )
Aliya.create(aliyah_number: 3, parsha_id: בחקתי.id, start_perek: 26,start_pasuk: 10, end_perek: 26, end_pasuk: 46 )
Aliya.create(aliyah_number: 4, parsha_id: בחקתי.id, start_perek: 27,start_pasuk: 1, end_perek: 27, end_pasuk: 15 )
Aliya.create(aliyah_number: 5, parsha_id: בחקתי.id, start_perek: 27,start_pasuk: 16, end_perek: 27, end_pasuk: 21 )
Aliya.create(aliyah_number: 6, parsha_id: בחקתי.id, start_perek: 27,start_pasuk: 22, end_perek: 27, end_pasuk: 28 )
Aliya.create(aliyah_number: 7, parsha_id: בחקתי.id, start_perek: 27,start_pasuk: 29, end_perek: 27, end_pasuk: 34 )
Aliya.create(aliyah_number: 8, parsha_id: בחקתי.id, start_perek: 27,start_pasuk: 32, end_perek: 27, end_pasuk: 34 )
Aliya.create(aliyah_number: 1, parsha_id: בהר_בחקתי.id, start_perek: 25,start_pasuk: 1, end_perek: 25, end_pasuk: 18 )
Aliya.create(aliyah_number: 2, parsha_id: בהר_בחקתי.id, start_perek: 25,start_pasuk: 19, end_perek: 25, end_pasuk: 28 )
Aliya.create(aliyah_number: 3, parsha_id: בהר_בחקתי.id, start_perek: 25,start_pasuk: 29, end_perek: 25, end_pasuk: 38 )
Aliya.create(aliyah_number: 4, parsha_id: בהר_בחקתי.id, start_perek: 25,start_pasuk: 39, end_perek: 26, end_pasuk: 9 )
Aliya.create(aliyah_number: 5, parsha_id: בהר_בחקתי.id, start_perek: 26,start_pasuk: 10, end_perek: 26, end_pasuk: 46 )
Aliya.create(aliyah_number: 6, parsha_id: בהר_בחקתי.id, start_perek: 27,start_pasuk: 1, end_perek: 27, end_pasuk: 15 )
Aliya.create(aliyah_number: 7, parsha_id: בהר_בחקתי.id, start_perek: 27,start_pasuk: 16, end_perek: 27, end_pasuk: 34 )
Aliya.create(aliyah_number: 8, parsha_id: בהר_בחקתי.id, start_perek: 27,start_pasuk: 32, end_perek: 27, end_pasuk: 34 )
Aliya.create(aliyah_number: 1, parsha_id: במדבר.id, start_perek: 1,start_pasuk: 1, end_perek: 1, end_pasuk: 19 )
Aliya.create(aliyah_number: 2, parsha_id: במדבר.id, start_perek: 1,start_pasuk: 20, end_perek: 1, end_pasuk: 54 )
Aliya.create(aliyah_number: 3, parsha_id: במדבר.id, start_perek: 2,start_pasuk: 1, end_perek: 2, end_pasuk: 34 )
Aliya.create(aliyah_number: 4, parsha_id: במדבר.id, start_perek: 3,start_pasuk: 1, end_perek: 3, end_pasuk: 13 )
Aliya.create(aliyah_number: 5, parsha_id: במדבר.id, start_perek: 3,start_pasuk: 14, end_perek: 3, end_pasuk: 39 )
Aliya.create(aliyah_number: 6, parsha_id: במדבר.id, start_perek: 3,start_pasuk: 40, end_perek: 3, end_pasuk: 51 )
Aliya.create(aliyah_number: 7, parsha_id: במדבר.id, start_perek: 4,start_pasuk: 1, end_perek: 4, end_pasuk: 20 )
Aliya.create(aliyah_number: 8, parsha_id: במדבר.id, start_perek: 4,start_pasuk: 17, end_perek: 4, end_pasuk: 20 )
Aliya.create(aliyah_number: 1, parsha_id: נשא.id, start_perek: 4,start_pasuk: 21, end_perek: 4, end_pasuk: 37 )
Aliya.create(aliyah_number: 2, parsha_id: נשא.id, start_perek: 4,start_pasuk: 38, end_perek: 4, end_pasuk: 49 )
Aliya.create(aliyah_number: 3, parsha_id: נשא.id, start_perek: 5,start_pasuk: 1, end_perek: 5, end_pasuk: 10 )
Aliya.create(aliyah_number: 4, parsha_id: נשא.id, start_perek: 5,start_pasuk: 11, end_perek: 6, end_pasuk: 27 )
Aliya.create(aliyah_number: 5, parsha_id: נשא.id, start_perek: 7,start_pasuk: 1, end_perek: 7, end_pasuk: 41 )
Aliya.create(aliyah_number: 6, parsha_id: נשא.id, start_perek: 7,start_pasuk: 42, end_perek: 7, end_pasuk: 71 )
Aliya.create(aliyah_number: 7, parsha_id: נשא.id, start_perek: 7,start_pasuk: 72, end_perek: 7, end_pasuk: 89 )
Aliya.create(aliyah_number: 8, parsha_id: נשא.id, start_perek: 7,start_pasuk: 87, end_perek: 7, end_pasuk: 89 )
Aliya.create(aliyah_number: 1, parsha_id: בהעלתך.id, start_perek: 8,start_pasuk: 1, end_perek: 8, end_pasuk: 14 )
Aliya.create(aliyah_number: 2, parsha_id: בהעלתך.id, start_perek: 8,start_pasuk: 15, end_perek: 8, end_pasuk: 26 )
Aliya.create(aliyah_number: 3, parsha_id: בהעלתך.id, start_perek: 9,start_pasuk: 1, end_perek: 9, end_pasuk: 14 )
Aliya.create(aliyah_number: 4, parsha_id: בהעלתך.id, start_perek: 9,start_pasuk: 15, end_perek: 10, end_pasuk: 10 )
Aliya.create(aliyah_number: 5, parsha_id: בהעלתך.id, start_perek: 10,start_pasuk: 11, end_perek: 10, end_pasuk: 34 )
Aliya.create(aliyah_number: 6, parsha_id: בהעלתך.id, start_perek: 10,start_pasuk: 35, end_perek: 11, end_pasuk: 29 )
Aliya.create(aliyah_number: 7, parsha_id: בהעלתך.id, start_perek: 11,start_pasuk: 30, end_perek: 12, end_pasuk: 16 )
Aliya.create(aliyah_number: 8, parsha_id: בהעלתך.id, start_perek: 12,start_pasuk: 14, end_perek: 12, end_pasuk: 16 )
Aliya.create(aliyah_number: 1, parsha_id: שלח.id, start_perek: 13,start_pasuk: 1, end_perek: 13, end_pasuk: 20 )
Aliya.create(aliyah_number: 2, parsha_id: שלח.id, start_perek: 13,start_pasuk: 21, end_perek: 14, end_pasuk: 7 )
Aliya.create(aliyah_number: 3, parsha_id: שלח.id, start_perek: 14,start_pasuk: 8, end_perek: 14, end_pasuk: 25 )
Aliya.create(aliyah_number: 4, parsha_id: שלח.id, start_perek: 14,start_pasuk: 26, end_perek: 15, end_pasuk: 7 )
Aliya.create(aliyah_number: 5, parsha_id: שלח.id, start_perek: 15,start_pasuk: 8, end_perek: 15, end_pasuk: 16 )
Aliya.create(aliyah_number: 6, parsha_id: שלח.id, start_perek: 15,start_pasuk: 17, end_perek: 15, end_pasuk: 26 )
Aliya.create(aliyah_number: 7, parsha_id: שלח.id, start_perek: 15,start_pasuk: 27, end_perek: 15, end_pasuk: 41 )
Aliya.create(aliyah_number: 8, parsha_id: שלח.id, start_perek: 15,start_pasuk: 37, end_perek: 15, end_pasuk: 41 )
Aliya.create(aliyah_number: 1, parsha_id: קרח.id, start_perek: 16,start_pasuk: 1, end_perek: 16, end_pasuk: 13 )
Aliya.create(aliyah_number: 2, parsha_id: קרח.id, start_perek: 16,start_pasuk: 14, end_perek: 16, end_pasuk: 19 )
Aliya.create(aliyah_number: 3, parsha_id: קרח.id, start_perek: 16,start_pasuk: 20, end_perek: 17, end_pasuk: 8 )
Aliya.create(aliyah_number: 4, parsha_id: קרח.id, start_perek: 17,start_pasuk: 9, end_perek: 17, end_pasuk: 15 )
Aliya.create(aliyah_number: 5, parsha_id: קרח.id, start_perek: 17,start_pasuk: 16, end_perek: 17, end_pasuk: 24 )
Aliya.create(aliyah_number: 6, parsha_id: קרח.id, start_perek: 17,start_pasuk: 25, end_perek: 18, end_pasuk: 20 )
Aliya.create(aliyah_number: 7, parsha_id: קרח.id, start_perek: 18,start_pasuk: 21, end_perek: 18, end_pasuk: 32 )
Aliya.create(aliyah_number: 8, parsha_id: קרח.id, start_perek: 18,start_pasuk: 30, end_perek: 18, end_pasuk: 32 )
Aliya.create(aliyah_number: 1, parsha_id: חקת.id, start_perek: 19,start_pasuk: 1, end_perek: 19, end_pasuk: 17 )
Aliya.create(aliyah_number: 2, parsha_id: חקת.id, start_perek: 19,start_pasuk: 18, end_perek: 20, end_pasuk: 6 )
Aliya.create(aliyah_number: 3, parsha_id: חקת.id, start_perek: 20,start_pasuk: 7, end_perek: 20, end_pasuk: 13 )
Aliya.create(aliyah_number: 4, parsha_id: חקת.id, start_perek: 20,start_pasuk: 14, end_perek: 20, end_pasuk: 21 )
Aliya.create(aliyah_number: 5, parsha_id: חקת.id, start_perek: 20,start_pasuk: 22, end_perek: 21, end_pasuk: 9 )
Aliya.create(aliyah_number: 6, parsha_id: חקת.id, start_perek: 21,start_pasuk: 10, end_perek: 21, end_pasuk: 20 )
Aliya.create(aliyah_number: 7, parsha_id: חקת.id, start_perek: 21,start_pasuk: 21, end_perek: 22, end_pasuk: 1 )
Aliya.create(aliyah_number: 8, parsha_id: חקת.id, start_perek: 21,start_pasuk: 34, end_perek: 22, end_pasuk: 1 )
Aliya.create(aliyah_number: 1, parsha_id: בלק.id, start_perek: 22,start_pasuk: 2, end_perek: 22, end_pasuk: 12 )
Aliya.create(aliyah_number: 2, parsha_id: בלק.id, start_perek: 22,start_pasuk: 13, end_perek: 22, end_pasuk: 20 )
Aliya.create(aliyah_number: 3, parsha_id: בלק.id, start_perek: 22,start_pasuk: 21, end_perek: 22, end_pasuk: 38 )
Aliya.create(aliyah_number: 4, parsha_id: בלק.id, start_perek: 22,start_pasuk: 39, end_perek: 23, end_pasuk: 12 )
Aliya.create(aliyah_number: 5, parsha_id: בלק.id, start_perek: 23,start_pasuk: 13, end_perek: 23, end_pasuk: 26 )
Aliya.create(aliyah_number: 6, parsha_id: בלק.id, start_perek: 23,start_pasuk: 27, end_perek: 24, end_pasuk: 13 )
Aliya.create(aliyah_number: 7, parsha_id: בלק.id, start_perek: 24,start_pasuk: 14, end_perek: 25, end_pasuk: 9 )
Aliya.create(aliyah_number: 8, parsha_id: בלק.id, start_perek: 25,start_pasuk: 7, end_perek: 25, end_pasuk: 9 )
Aliya.create(aliyah_number: 1, parsha_id: חקת_בלק.id, start_perek: 19,start_pasuk: 1, end_perek: 20, end_pasuk: 6 )
Aliya.create(aliyah_number: 2, parsha_id: חקת_בלק.id, start_perek: 20,start_pasuk: 7, end_perek: 20, end_pasuk: 21 )
Aliya.create(aliyah_number: 3, parsha_id: חקת_בלק.id, start_perek: 20,start_pasuk: 22, end_perek: 21, end_pasuk: 20 )
Aliya.create(aliyah_number: 4, parsha_id: חקת_בלק.id, start_perek: 21,start_pasuk: 21, end_perek: 22, end_pasuk: 12 )
Aliya.create(aliyah_number: 5, parsha_id: חקת_בלק.id, start_perek: 22,start_pasuk: 13, end_perek: 22, end_pasuk: 38 )
Aliya.create(aliyah_number: 6, parsha_id: חקת_בלק.id, start_perek: 22,start_pasuk: 39, end_perek: 23, end_pasuk: 26 )
Aliya.create(aliyah_number: 7, parsha_id: חקת_בלק.id, start_perek: 23,start_pasuk: 27, end_perek: 25, end_pasuk: 9 )
Aliya.create(aliyah_number: 8, parsha_id: חקת_בלק.id, start_perek: 25,start_pasuk: 7, end_perek: 25, end_pasuk: 9 )
Aliya.create(aliyah_number: 1, parsha_id: פנחס.id, start_perek: 25,start_pasuk: 10, end_perek: 26, end_pasuk: 4 )
Aliya.create(aliyah_number: 2, parsha_id: פנחס.id, start_perek: 26,start_pasuk: 5, end_perek: 26, end_pasuk: 51 )
Aliya.create(aliyah_number: 3, parsha_id: פנחס.id, start_perek: 26,start_pasuk: 52, end_perek: 27, end_pasuk: 5 )
Aliya.create(aliyah_number: 4, parsha_id: פנחס.id, start_perek: 27,start_pasuk: 6, end_perek: 27, end_pasuk: 23 )
Aliya.create(aliyah_number: 5, parsha_id: פנחס.id, start_perek: 28,start_pasuk: 1, end_perek: 28, end_pasuk: 15 )
Aliya.create(aliyah_number: 6, parsha_id: פנחס.id, start_perek: 28,start_pasuk: 16, end_perek: 29, end_pasuk: 11 )
Aliya.create(aliyah_number: 7, parsha_id: פנחס.id, start_perek: 29,start_pasuk: 12, end_perek: 30, end_pasuk: 1 )
Aliya.create(aliyah_number: 8, parsha_id: פנחס.id, start_perek: 29,start_pasuk: 35, end_perek: 30, end_pasuk: 1 )
Aliya.create(aliyah_number: 1, parsha_id: מטות.id, start_perek: 30,start_pasuk: 2, end_perek: 30, end_pasuk: 17 )
Aliya.create(aliyah_number: 2, parsha_id: מטות.id, start_perek: 31,start_pasuk: 1, end_perek: 31, end_pasuk: 12 )
Aliya.create(aliyah_number: 3, parsha_id: מטות.id, start_perek: 31,start_pasuk: 13, end_perek: 31, end_pasuk: 24 )
Aliya.create(aliyah_number: 4, parsha_id: מטות.id, start_perek: 31,start_pasuk: 25, end_perek: 31, end_pasuk: 41 )
Aliya.create(aliyah_number: 5, parsha_id: מטות.id, start_perek: 31,start_pasuk: 42, end_perek: 31, end_pasuk: 54 )
Aliya.create(aliyah_number: 6, parsha_id: מטות.id, start_perek: 32,start_pasuk: 1, end_perek: 32, end_pasuk: 19 )
Aliya.create(aliyah_number: 7, parsha_id: מטות.id, start_perek: 32,start_pasuk: 20, end_perek: 32, end_pasuk: 42 )
Aliya.create(aliyah_number: 8, parsha_id: מטות.id, start_perek: 32,start_pasuk: 39, end_perek: 32, end_pasuk: 42 )
Aliya.create(aliyah_number: 1, parsha_id: מסעי.id, start_perek: 33,start_pasuk: 1, end_perek: 33, end_pasuk: 10 )
Aliya.create(aliyah_number: 2, parsha_id: מסעי.id, start_perek: 33,start_pasuk: 11, end_perek: 33, end_pasuk: 49 )
Aliya.create(aliyah_number: 3, parsha_id: מסעי.id, start_perek: 33,start_pasuk: 50, end_perek: 34, end_pasuk: 15 )
Aliya.create(aliyah_number: 4, parsha_id: מסעי.id, start_perek: 34,start_pasuk: 16, end_perek: 34, end_pasuk: 29 )
Aliya.create(aliyah_number: 5, parsha_id: מסעי.id, start_perek: 35,start_pasuk: 1, end_perek: 35, end_pasuk: 8 )
Aliya.create(aliyah_number: 6, parsha_id: מסעי.id, start_perek: 35,start_pasuk: 9, end_perek: 35, end_pasuk: 34 )
Aliya.create(aliyah_number: 7, parsha_id: מסעי.id, start_perek: 36,start_pasuk: 1, end_perek: 36, end_pasuk: 13 )
Aliya.create(aliyah_number: 8, parsha_id: מסעי.id, start_perek: 36,start_pasuk: 11, end_perek: 36, end_pasuk: 13 )
Aliya.create(aliyah_number: 1, parsha_id: מטות_מסעי.id, start_perek: 30,start_pasuk: 2, end_perek: 31, end_pasuk: 12 )
Aliya.create(aliyah_number: 2, parsha_id: מטות_מסעי.id, start_perek: 31,start_pasuk: 13, end_perek: 31, end_pasuk: 54 )
Aliya.create(aliyah_number: 3, parsha_id: מטות_מסעי.id, start_perek: 32,start_pasuk: 1, end_perek: 32, end_pasuk: 19 )
Aliya.create(aliyah_number: 4, parsha_id: מטות_מסעי.id, start_perek: 32,start_pasuk: 20, end_perek: 33, end_pasuk: 49 )
Aliya.create(aliyah_number: 5, parsha_id: מטות_מסעי.id, start_perek: 33,start_pasuk: 50, end_perek: 34, end_pasuk: 15 )
Aliya.create(aliyah_number: 6, parsha_id: מטות_מסעי.id, start_perek: 34,start_pasuk: 16, end_perek: 35, end_pasuk: 8 )
Aliya.create(aliyah_number: 7, parsha_id: מטות_מסעי.id, start_perek: 35,start_pasuk: 9, end_perek: 36, end_pasuk: 13 )
Aliya.create(aliyah_number: 8, parsha_id: מטות_מסעי.id, start_perek: 36,start_pasuk: 11, end_perek: 36, end_pasuk: 13 )
Aliya.create(aliyah_number: 1, parsha_id: דברים.id, start_perek: 1,start_pasuk: 1, end_perek: 1, end_pasuk: 10 )
Aliya.create(aliyah_number: 2, parsha_id: דברים.id, start_perek: 1,start_pasuk: 11, end_perek: 1, end_pasuk: 21 )
Aliya.create(aliyah_number: 3, parsha_id: דברים.id, start_perek: 1,start_pasuk: 22, end_perek: 1, end_pasuk: 38 )
Aliya.create(aliyah_number: 4, parsha_id: דברים.id, start_perek: 1,start_pasuk: 39, end_perek: 2, end_pasuk: 1 )
Aliya.create(aliyah_number: 5, parsha_id: דברים.id, start_perek: 2,start_pasuk: 2, end_perek: 2, end_pasuk: 30 )
Aliya.create(aliyah_number: 6, parsha_id: דברים.id, start_perek: 2,start_pasuk: 31, end_perek: 3, end_pasuk: 14 )
Aliya.create(aliyah_number: 7, parsha_id: דברים.id, start_perek: 3,start_pasuk: 15, end_perek: 3, end_pasuk: 22 )
Aliya.create(aliyah_number: 8, parsha_id: דברים.id, start_perek: 3,start_pasuk: 20, end_perek: 3, end_pasuk: 22 )
Aliya.create(aliyah_number: 1, parsha_id: ואתחנן.id, start_perek: 3,start_pasuk: 23, end_perek: 4, end_pasuk: 4 )
Aliya.create(aliyah_number: 2, parsha_id: ואתחנן.id, start_perek: 4,start_pasuk: 5, end_perek: 4, end_pasuk: 40 )
Aliya.create(aliyah_number: 3, parsha_id: ואתחנן.id, start_perek: 4,start_pasuk: 41, end_perek: 4, end_pasuk: 49 )
Aliya.create(aliyah_number: 4, parsha_id: ואתחנן.id, start_perek: 5,start_pasuk: 1, end_perek: 5, end_pasuk: 18 )
Aliya.create(aliyah_number: 5, parsha_id: ואתחנן.id, start_perek: 5,start_pasuk: 19, end_perek: 6, end_pasuk: 3 )
Aliya.create(aliyah_number: 6, parsha_id: ואתחנן.id, start_perek: 6,start_pasuk: 4, end_perek: 6, end_pasuk: 25 )
Aliya.create(aliyah_number: 7, parsha_id: ואתחנן.id, start_perek: 7,start_pasuk: 1, end_perek: 7, end_pasuk: 11 )
Aliya.create(aliyah_number: 8, parsha_id: ואתחנן.id, start_perek: 7,start_pasuk: 9, end_perek: 7, end_pasuk: 11 )
Aliya.create(aliyah_number: 1, parsha_id: עקב.id, start_perek: 7,start_pasuk: 12, end_perek: 8, end_pasuk: 10 )
Aliya.create(aliyah_number: 2, parsha_id: עקב.id, start_perek: 8,start_pasuk: 11, end_perek: 9, end_pasuk: 3 )
Aliya.create(aliyah_number: 3, parsha_id: עקב.id, start_perek: 9,start_pasuk: 4, end_perek: 9, end_pasuk: 29 )
Aliya.create(aliyah_number: 4, parsha_id: עקב.id, start_perek: 10,start_pasuk: 1, end_perek: 10, end_pasuk: 11 )
Aliya.create(aliyah_number: 5, parsha_id: עקב.id, start_perek: 10,start_pasuk: 12, end_perek: 11, end_pasuk: 9 )
Aliya.create(aliyah_number: 6, parsha_id: עקב.id, start_perek: 11,start_pasuk: 10, end_perek: 11, end_pasuk: 21 )
Aliya.create(aliyah_number: 7, parsha_id: עקב.id, start_perek: 11,start_pasuk: 22, end_perek: 11, end_pasuk: 25 )
Aliya.create(aliyah_number: 8, parsha_id: עקב.id, start_perek: 11,start_pasuk: 22, end_perek: 11, end_pasuk: 25 )
Aliya.create(aliyah_number: 1, parsha_id: ראה.id, start_perek: 11,start_pasuk: 26, end_perek: 12, end_pasuk: 10 )
Aliya.create(aliyah_number: 2, parsha_id: ראה.id, start_perek: 12,start_pasuk: 11, end_perek: 12, end_pasuk: 28 )
Aliya.create(aliyah_number: 3, parsha_id: ראה.id, start_perek: 12,start_pasuk: 29, end_perek: 13, end_pasuk: 19 )
Aliya.create(aliyah_number: 4, parsha_id: ראה.id, start_perek: 14,start_pasuk: 1, end_perek: 14, end_pasuk: 21 )
Aliya.create(aliyah_number: 5, parsha_id: ראה.id, start_perek: 14,start_pasuk: 22, end_perek: 14, end_pasuk: 29 )
Aliya.create(aliyah_number: 6, parsha_id: ראה.id, start_perek: 15,start_pasuk: 1, end_perek: 15, end_pasuk: 18 )
Aliya.create(aliyah_number: 7, parsha_id: ראה.id, start_perek: 15,start_pasuk: 19, end_perek: 16, end_pasuk: 17 )
Aliya.create(aliyah_number: 8, parsha_id: ראה.id, start_perek: 16,start_pasuk: 13, end_perek: 16, end_pasuk: 17 )
Aliya.create(aliyah_number: 1, parsha_id: שופטים.id, start_perek: 16,start_pasuk: 18, end_perek: 17, end_pasuk: 13 )
Aliya.create(aliyah_number: 2, parsha_id: שופטים.id, start_perek: 17,start_pasuk: 14, end_perek: 17, end_pasuk: 20 )
Aliya.create(aliyah_number: 3, parsha_id: שופטים.id, start_perek: 18,start_pasuk: 1, end_perek: 18, end_pasuk: 5 )
Aliya.create(aliyah_number: 4, parsha_id: שופטים.id, start_perek: 18,start_pasuk: 6, end_perek: 18, end_pasuk: 13 )
Aliya.create(aliyah_number: 5, parsha_id: שופטים.id, start_perek: 18,start_pasuk: 14, end_perek: 19, end_pasuk: 13 )
Aliya.create(aliyah_number: 6, parsha_id: שופטים.id, start_perek: 19,start_pasuk: 14, end_perek: 20, end_pasuk: 9 )
Aliya.create(aliyah_number: 7, parsha_id: שופטים.id, start_perek: 20,start_pasuk: 10, end_perek: 21, end_pasuk: 9 )
Aliya.create(aliyah_number: 8, parsha_id: שופטים.id, start_perek: 21,start_pasuk: 7, end_perek: 21, end_pasuk: 9 )
Aliya.create(aliyah_number: 1, parsha_id: כי_תצא.id, start_perek: 21,start_pasuk: 10, end_perek: 21, end_pasuk: 21 )
Aliya.create(aliyah_number: 2, parsha_id: כי_תצא.id, start_perek: 21,start_pasuk: 22, end_perek: 22, end_pasuk: 7 )
Aliya.create(aliyah_number: 3, parsha_id: כי_תצא.id, start_perek: 22,start_pasuk: 8, end_perek: 23, end_pasuk: 7 )
Aliya.create(aliyah_number: 4, parsha_id: כי_תצא.id, start_perek: 23,start_pasuk: 8, end_perek: 23, end_pasuk: 24 )
Aliya.create(aliyah_number: 5, parsha_id: כי_תצא.id, start_perek: 23,start_pasuk: 25, end_perek: 24, end_pasuk: 4 )
Aliya.create(aliyah_number: 6, parsha_id: כי_תצא.id, start_perek: 24,start_pasuk: 5, end_perek: 24, end_pasuk: 13 )
Aliya.create(aliyah_number: 7, parsha_id: כי_תצא.id, start_perek: 24,start_pasuk: 14, end_perek: 25, end_pasuk: 19 )
Aliya.create(aliyah_number: 8, parsha_id: כי_תצא.id, start_perek: 25,start_pasuk: 17, end_perek: 25, end_pasuk: 19 )
Aliya.create(aliyah_number: 1, parsha_id: כי_תבא.id, start_perek: 26,start_pasuk: 1, end_perek: 26, end_pasuk: 11 )
Aliya.create(aliyah_number: 2, parsha_id: כי_תבא.id, start_perek: 26,start_pasuk: 12, end_perek: 26, end_pasuk: 15 )
Aliya.create(aliyah_number: 3, parsha_id: כי_תבא.id, start_perek: 26,start_pasuk: 16, end_perek: 26, end_pasuk: 19 )
Aliya.create(aliyah_number: 4, parsha_id: כי_תבא.id, start_perek: 27,start_pasuk: 1, end_perek: 27, end_pasuk: 10 )
Aliya.create(aliyah_number: 5, parsha_id: כי_תבא.id, start_perek: 27,start_pasuk: 11, end_perek: 28, end_pasuk: 6 )
Aliya.create(aliyah_number: 6, parsha_id: כי_תבא.id, start_perek: 28,start_pasuk: 7, end_perek: 28, end_pasuk: 69 )
Aliya.create(aliyah_number: 7, parsha_id: כי_תבא.id, start_perek: 29,start_pasuk: 1, end_perek: 29, end_pasuk: 8 )
Aliya.create(aliyah_number: 8, parsha_id: כי_תבא.id, start_perek: 29,start_pasuk: 6, end_perek: 29, end_pasuk: 8 )
Aliya.create(aliyah_number: 1, parsha_id: נצבים.id, start_perek: 29,start_pasuk: 9, end_perek: 29, end_pasuk: 11 )
Aliya.create(aliyah_number: 2, parsha_id: נצבים.id, start_perek: 29,start_pasuk: 12, end_perek: 29, end_pasuk: 14 )
Aliya.create(aliyah_number: 3, parsha_id: נצבים.id, start_perek: 29,start_pasuk: 15, end_perek: 29, end_pasuk: 28 )
Aliya.create(aliyah_number: 4, parsha_id: נצבים.id, start_perek: 30,start_pasuk: 1, end_perek: 30, end_pasuk: 6 )
Aliya.create(aliyah_number: 5, parsha_id: נצבים.id, start_perek: 30,start_pasuk: 7, end_perek: 30, end_pasuk: 10 )
Aliya.create(aliyah_number: 6, parsha_id: נצבים.id, start_perek: 30,start_pasuk: 11, end_perek: 30, end_pasuk: 14 )
Aliya.create(aliyah_number: 7, parsha_id: נצבים.id, start_perek: 30,start_pasuk: 15, end_perek: 30, end_pasuk: 20 )
Aliya.create(aliyah_number: 8, parsha_id: נצבים.id, start_perek: 30,start_pasuk: 15, end_perek: 30, end_pasuk: 20 )
Aliya.create(aliyah_number: 1, parsha_id: וילך.id, start_perek: 31,start_pasuk: 1, end_perek: 31, end_pasuk: 3 )
Aliya.create(aliyah_number: 2, parsha_id: וילך.id, start_perek: 31,start_pasuk: 4, end_perek: 31, end_pasuk: 6 )
Aliya.create(aliyah_number: 3, parsha_id: וילך.id, start_perek: 31,start_pasuk: 7, end_perek: 31, end_pasuk: 9 )
Aliya.create(aliyah_number: 4, parsha_id: וילך.id, start_perek: 31,start_pasuk: 10, end_perek: 31, end_pasuk: 13 )
Aliya.create(aliyah_number: 5, parsha_id: וילך.id, start_perek: 31,start_pasuk: 14, end_perek: 31, end_pasuk: 19 )
Aliya.create(aliyah_number: 6, parsha_id: וילך.id, start_perek: 31,start_pasuk: 20, end_perek: 31, end_pasuk: 24 )
Aliya.create(aliyah_number: 7, parsha_id: וילך.id, start_perek: 31,start_pasuk: 25, end_perek: 31, end_pasuk: 30 )
Aliya.create(aliyah_number: 8, parsha_id: וילך.id, start_perek: 31,start_pasuk: 28, end_perek: 31, end_pasuk: 30 )
Aliya.create(aliyah_number: 1, parsha_id: נצבים_וילך.id, start_perek: 29,start_pasuk: 9, end_perek: 29, end_pasuk: 28 )
Aliya.create(aliyah_number: 2, parsha_id: נצבים_וילך.id, start_perek: 30,start_pasuk: 1, end_perek: 30, end_pasuk: 6 )
Aliya.create(aliyah_number: 3, parsha_id: נצבים_וילך.id, start_perek: 30,start_pasuk: 7, end_perek: 30, end_pasuk: 14 )
Aliya.create(aliyah_number: 4, parsha_id: נצבים_וילך.id, start_perek: 30,start_pasuk: 15, end_perek: 31, end_pasuk: 6 )
Aliya.create(aliyah_number: 5, parsha_id: נצבים_וילך.id, start_perek: 31,start_pasuk: 7, end_perek: 31, end_pasuk: 13 )
Aliya.create(aliyah_number: 6, parsha_id: נצבים_וילך.id, start_perek: 31,start_pasuk: 14, end_perek: 31, end_pasuk: 19 )
Aliya.create(aliyah_number: 7, parsha_id: נצבים_וילך.id, start_perek: 31,start_pasuk: 20, end_perek: 31, end_pasuk: 30 )
Aliya.create(aliyah_number: 8, parsha_id: נצבים_וילך.id, start_perek: 31,start_pasuk: 28, end_perek: 31, end_pasuk: 30 )
Aliya.create(aliyah_number: 1, parsha_id: האזינו.id, start_perek: 32,start_pasuk: 1, end_perek: 32, end_pasuk: 6 )
Aliya.create(aliyah_number: 2, parsha_id: האזינו.id, start_perek: 32,start_pasuk: 7, end_perek: 32, end_pasuk: 12 )
Aliya.create(aliyah_number: 3, parsha_id: האזינו.id, start_perek: 32,start_pasuk: 13, end_perek: 32, end_pasuk: 18 )
Aliya.create(aliyah_number: 4, parsha_id: האזינו.id, start_perek: 32,start_pasuk: 19, end_perek: 32, end_pasuk: 28 )
Aliya.create(aliyah_number: 5, parsha_id: האזינו.id, start_perek: 32,start_pasuk: 29, end_perek: 32, end_pasuk: 39 )
Aliya.create(aliyah_number: 6, parsha_id: האזינו.id, start_perek: 32,start_pasuk: 40, end_perek: 32, end_pasuk: 43 )
Aliya.create(aliyah_number: 7, parsha_id: האזינו.id, start_perek: 32,start_pasuk: 44, end_perek: 32, end_pasuk: 52 )
Aliya.create(aliyah_number: 8, parsha_id: האזינו.id, start_perek: 32,start_pasuk: 48, end_perek: 32, end_pasuk: 52 )
Aliya.create(aliyah_number: 1, parsha_id: וזאת_הברכה.id, start_perek: 33,start_pasuk: 1, end_perek: 33, end_pasuk: 7 )
Aliya.create(aliyah_number: 2, parsha_id: וזאת_הברכה.id, start_perek: 33,start_pasuk: 8, end_perek: 33, end_pasuk: 12 )
Aliya.create(aliyah_number: 3, parsha_id: וזאת_הברכה.id, start_perek: 33,start_pasuk: 13, end_perek: 33, end_pasuk: 17 )
Aliya.create(aliyah_number: 4, parsha_id: וזאת_הברכה.id, start_perek: 33,start_pasuk: 18, end_perek: 33, end_pasuk: 21 )
Aliya.create(aliyah_number: 5, parsha_id: וזאת_הברכה.id, start_perek: 33,start_pasuk: 22, end_perek: 33, end_pasuk: 26 )
Aliya.create(aliyah_number: 6, parsha_id: וזאת_הברכה.id, start_perek: 33,start_pasuk: 27, end_perek: 33, end_pasuk: 29 )
Aliya.create(aliyah_number: 7, parsha_id: וזאת_הברכה.id, start_perek: 34,start_pasuk: 1, end_perek: 34, end_pasuk: 12 )

